
import { Language } from '../types';

export const translations: Record<string, Record<Language, string>> = {
  // Common UI
  'app_title': { [Language.EN]: 'AgroAI', [Language.HI]: 'एग्रो एआई', [Language.BN]: 'এগ্রো এআই', [Language.MR]: 'एग्रो एआय', [Language.TE]: 'అగ్రో ఏఐ', [Language.TA]: 'அக்ரோ ஏஐ', [Language.GU]: 'એગ્રો એઆઈ', [Language.UR]: 'ایگرو اے آئی', [Language.KN]: 'ಅಗ್ರೋ ಎಐ', [Language.OR]: 'ଏଗ୍ରୋ ଏଆଇ', [Language.ML]: 'അഗ്രো എഐ', [Language.PA]: 'ਐਗਰੋ ਏਆਈ', [Language.AS]: 'এগ্ৰো এআই' },
  'smart_farming': { [Language.EN]: 'Smart Farming Assistant', [Language.HI]: 'स्मार्ट खेती सहायक', [Language.BN]: 'স্মার্ট ফার্মিং সহকারী', [Language.MR]: 'स्मार्ट शेती सहाय्यक', [Language.TE]: 'స్మార్ట్ ఫార్మింగ్ అసిస్టెంట్', [Language.TA]: 'ஸ்மார்ட் விவசாய உதவியாளர்', [Language.GU]: 'સ્માર્ટ ફાર્મિંગ સહાયક', [Language.UR]: 'اسمارٹ فارمنگ اسسٹنٹ', [Language.KN]: 'ಸ್ಮಾರ್ಟ್ ಫಾರ್ಮಿಂಗ್ ಅಸಿಸ್ಟೆಂಟ್', [Language.OR]: 'ସ୍ମାର୍ଟ ଚାଷ ସହାୟକ', [Language.ML]: 'സ്മാർട്ട് ഫാമിംഗ് അസിസ്റ്റന്റ്', [Language.PA]: 'ਸਮਾਰਟ ਫਾਰਮਿੰਗ ಸਹਾਇਕ', [Language.AS]: 'স্মাৰ্ট ফাৰ্মিং সহায়ক' },
  'cancel': { [Language.EN]: 'Cancel', [Language.HI]: 'रद्द करें', [Language.BN]: 'বাতিল করুন', [Language.MR]: 'रद्द करा', [Language.TE]: 'రద్దు చేయండి', [Language.TA]: 'ரத்து செய்', [Language.GU]: 'રદ કરો', [Language.UR]: 'منسوخ کریں', [Language.KN]: 'ರದ್ದುಮಾಡಿ', [Language.OR]: 'ବାତିଲ୍ କରନ୍ତୁ', [Language.ML]: 'റദ്ദാക്കുക', [Language.PA]: 'ਰੱਦ ਕਰੋ', [Language.AS]: 'বাতিল কৰক' },
  
  // Navigation
  'nav_home': { [Language.EN]: 'Home', [Language.HI]: 'होम', [Language.BN]: 'হোম', [Language.MR]: 'होम', [Language.TE]: 'హోమ్', [Language.TA]: 'முகப்பு', [Language.GU]: 'હોમ', [Language.UR]: 'ہوم', [Language.KN]: 'ಹೋಮ್', [Language.OR]: 'ମୁଖ୍ୟ ପୃଷ୍ଠା', [Language.ML]: 'ഹോം', [Language.PA]: 'ਮੁੱਖ', [Language.AS]: 'গৃহ' },
  'nav_doctor': { [Language.EN]: 'Doctor', [Language.HI]: 'डॉक्टर', [Language.BN]: 'ডাক্তার', [Language.MR]: 'डॉक्टर', [Language.TE]: 'డాక్టర్', [Language.TA]: 'மருத்துவர்', [Language.GU]: 'ડોક્ટર', [Language.UR]: 'ڈاکٹر', [Language.KN]: 'ಡಾಕ್ಟರ್', [Language.OR]: 'ଡାକ୍ତର', [Language.ML]: 'ഡോക്ടർ', [Language.PA]: 'ਡਾਕਟਰ', [Language.AS]: 'চিকিৎসক' },
  'nav_notes': { [Language.EN]: 'Notes', [Language.HI]: 'नोट्स', [Language.BN]: 'নোট', [Language.MR]: 'नोंदी', [Language.TE]: 'నోట్స్', [Language.TA]: 'குறிப்புகள்', [Language.GU]: 'નોંધો', [Language.UR]: 'نوٹس', [Language.KN]: 'ಟಿಪ್ಪಣಿಗಳು', [Language.OR]: 'ନୋଟ୍ସ', [Language.ML]: 'കുറിപ്പുകൾ', [Language.PA]: 'ਨੋਟ', [Language.AS]: 'টোকা' },
  'nav_expert': { [Language.EN]: 'Expert', [Language.HI]: 'विशेषज्ञ', [Language.BN]: 'বিশেষজ্ঞ', [Language.MR]: 'तज्ज्ञ', [Language.TE]: 'నిపుణుడు', [Language.TA]: 'நிபுணர்', [Language.GU]: 'નિષ્ણાત', [Language.UR]: 'ماہر', [Language.KN]: 'ತಜ್ಞ', [Language.OR]: 'ବିଶେଷଜ୍ଞ', [Language.ML]: 'വിദഗ്ദ്ധൻ', [Language.PA]: 'ਮਾਹਰ', [Language.AS]: 'বিশেষজ্ঞ' },

  // Auth
  'login_welcome': { [Language.EN]: 'Welcome Back', [Language.HI]: 'स्वागत है', [Language.BN]: 'স্বাগতম', [Language.MR]: 'स्वागत आहे', [Language.TE]: 'స్వాగతం', [Language.TA]: 'வரவேற்பு', [Language.GU]: 'સ્વાગત છે', [Language.UR]: 'خوش آمدید', [Language.KN]: 'ಸ್ವಾಗತ', [Language.OR]: 'ସ୍ୱାଗତ', [Language.ML]: 'സ്വാഗതം', [Language.PA]: 'ਜੀ ਆਇਆਂ ਨੂੰ', [Language.AS]: 'স্বাগতম' },
  'create_account': { [Language.EN]: 'Create Farmer Account', [Language.HI]: 'किसान खाता बनाएं', [Language.BN]: 'কৃষক অ্যাকাউন্ট তৈরি করুন', [Language.MR]: 'शेतकरी खाते तयार करा', [Language.TE]: 'రైతు ఖాతాను సృష్టించండి', [Language.TA]: 'விவசாயி கணக்கை உருவாக்கு', [Language.GU]: 'ખેડૂત ખાતું બનાવો', [Language.UR]: 'کسان اکاؤنٹ بنائیں', [Language.KN]: 'ರೈತ ಖಾತೆಯನ್ನು ರಚಿಸಿ', [Language.OR]: 'ଚାଷୀ ଆକାଉଣ୍ଟ ଖୋଲନ୍ତୁ', [Language.ML]: 'കർഷക അക്കൗണ്ട് സൃഷ്ടിക്കുക', [Language.PA]: 'ਕਿਸਾਨ ਖਾਤਾ ਬਣਾਓ', [Language.AS]: 'কৃষক একাউণ্ট সৃষ্টি কৰক' },
  'login_to_farm': { [Language.EN]: 'Login to Farm', [Language.HI]: 'लॉगिन करें', [Language.BN]: 'লগইন করুন', [Language.MR]: 'लॉगिन करा', [Language.TE]: 'లాగిన్', [Language.TA]: 'உள்நுழைக', [Language.GU]: 'લોગિન કરો', [Language.UR]: 'لاگ ان کریں', [Language.KN]: 'ಲಾಗಿನ್ ಮಾಡಿ', [Language.OR]: 'ଲଗଇନ୍ କରନ୍ତୁ', [Language.ML]: 'ലോഗിൻ ചെയ്യുക', [Language.PA]: 'ਲੌਗਇਨ ਕਰੋ', [Language.AS]: 'লগইন কৰক' },
  'start_farming': { [Language.EN]: 'Start Farming', [Language.HI]: 'खेती शुरू करें', [Language.BN]: 'চাষ শুরু করুন', [Language.MR]: 'शेती सुरू करा', [Language.TE]: 'వ్యవసాయం ప్రారంభించండి', [Language.TA]: 'விவசாயத்தைத் தொடங்குங்கள்', [Language.GU]: 'ખેતી શરૂ કરો', [Language.UR]: 'کاشتکاری شروع کریں', [Language.KN]: 'ವ್ಯವಸಾಯ ಪ್ರಾರಂಭಿಸಿ', [Language.OR]: 'ଚାଷ ଆରମ୍ଭ କରନ୍ତୁ', [Language.ML]: 'കൃഷി ആരംഭിക്കുക', [Language.PA]: 'ਖੇਤੀਬਾੜੀ ਸ਼ੁਰੂ ਕਰੋ', [Language.AS]: 'খেতি আৰম্ভ কৰক' },
  'full_name': { [Language.EN]: 'Full Name', [Language.HI]: 'पूरा नाम', [Language.BN]: 'পুরো নাম', [Language.MR]: 'पूर्ण नाव', [Language.TE]: 'పూర్తి పేరు', [Language.TA]: 'முழு பெயர்', [Language.GU]: 'પૂરું નામ', [Language.UR]: 'پورا نام', [Language.KN]: 'ಪೂರ್ಣ ಹೆಸರು', [Language.OR]: 'ପୂରା ନାମ', [Language.ML]: 'പൂർണ്ണനാമം', [Language.PA]: 'ਪੂਰਾ ਨਾਮ', [Language.AS]: 'পূৰ্ণ নাম' },
  'email': { [Language.EN]: 'Email Address', [Language.HI]: 'ईमेल पता', [Language.BN]: 'ইমেল ঠিকানা', [Language.MR]: 'ईमेल पत्ता', [Language.TE]: 'ఈమెయిల్', [Language.TA]: 'மின்னஞ்சல்', [Language.GU]: 'ઇમેઇલ સરનામું', [Language.UR]: 'ای میل پتہ', [Language.KN]: 'ಇಮೇಲ್ ವಿಳಾಸ', [Language.OR]: 'ଇମେଲ୍ ଠିକଣା', [Language.ML]: 'ഇമെയിൽ വിലാസം', [Language.PA]: 'ਈਮੇਲ ਪਤਾ', [Language.AS]: 'ইমেইল ঠিকনা' },
  'password': { [Language.EN]: 'Password', [Language.HI]: 'पासवर्ड', [Language.BN]: 'পাসওয়ার্ড', [Language.MR]: 'पासवर्ड', [Language.TE]: 'పాస్‌వర్డ్', [Language.TA]: 'கடவுச்சொல்', [Language.GU]: 'પાસવર્ડ', [Language.UR]: 'پاس ورڈ', [Language.KN]: 'ಪಾಸ್‌ವರ್ಡ್', [Language.OR]: 'ପାସୱାର୍ଡ', [Language.ML]: 'പാസ്‌വേഡ്', [Language.PA]: 'ਪਾਸਵਰਡ', [Language.AS]: 'পাছৱৰ্ড' },
  'new_to_app': { [Language.EN]: 'New to AgroAI? Create an account', [Language.HI]: 'एग्रो एआई में नए हैं? खाता बनाएं', [Language.BN]: 'এগ্রো এআই-তে নতুন? অ্যাকাউন্ট তৈরি করুন', [Language.MR]: 'एग्रो एआय वर नवीन आहात? खाते तयार करा', [Language.TE]: 'అగ్రో ఏఐ కొత్తదా? ఖాతాను సృష్టించండి', [Language.TA]: 'அக்ரோ ஏஐ-க்கு புதியவரா? கணக்கை உருவாக்குங்கள்', [Language.GU]: 'એગ્રો એઆઈ માં નવા છો? ખાતું બનાવો', [Language.UR]: 'ایگرو اے آئی میں نئے ہیں؟ اکاؤنٹ بنائیں', [Language.KN]: 'ಅಗ್ರೋ ಎಐಗೆ ಹೊಸಬರೇ? ಖಾತೆ ರಚಿಸಿ', [Language.OR]: 'ଏଗ୍ରୋ ଏଆଇ ରେ ନୂଆ କି? ଆକାଉଣ୍ଟ ଖୋଲନ୍ତୁ', [Language.ML]: 'അഗ്രോ എഐ-ൽ പുതിയതാണോ? അക്കൗണ്ട് സൃഷ്ടിക്കുക', [Language.PA]: 'ਐਗਰੋ ਏਆਈ ਵਿੱਚ ਨਵੇਂ ਹੋ? ਖਾਤਾ ਬਣਾਓ', [Language.AS]: 'এগ্ৰো এআইত নতুন নেকি? একাউণ্ট সৃষ্টি কৰক' },
  'already_have_account': { [Language.EN]: 'Already have an account? Login', [Language.HI]: 'पहले से ही एक खाता है? लॉगिन करें', [Language.BN]: 'আগে থেকেই অ্যাকাউন্ট আছে? লগইন করুন', [Language.MR]: 'आधीच खाते आहे का? लॉगिन करा', [Language.TE]: 'ఇప్పటికే ఖాతా ఉందా? లాగిన్ అవ్వండి', [Language.TA]: 'ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைக', [Language.GU]: 'પહેલાથી જ ખાતું છે? લોગિન કરો', [Language.UR]: 'پہلے سے ہی ایک اکاؤنٹ ہے؟ لاگ ان کریں', [Language.KN]: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ', [Language.OR]: 'ପୂର୍ବରୁ ଆକାଉଣ୍ଟ ଅଛି କି? ଲଗଇନ୍ କରନ୍ତୁ', [Language.ML]: 'ഇപ്പോൾ തന്നെ അക്കൗണ്ട് ഉണ്ടോ? ലോഗിൻ ചെയ്യുക', [Language.PA]: 'ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ? ਲੌਗਇਨ ਕਰੋ', [Language.AS]: 'ইতিমধ্যে একাউণ্ট আছে নেকি? লগইন কৰক' },

  // Dashboard
  'hello': { [Language.EN]: 'Hello', [Language.HI]: 'नमस्ते', [Language.BN]: 'হ্যালো', [Language.MR]: 'नमस्कार', [Language.TE]: 'హలో', [Language.TA]: 'வணக்கம்', [Language.GU]: 'હેલો', [Language.UR]: 'ہیلو', [Language.KN]: 'ಹಲೋ', [Language.OR]: 'ନମସ୍କାର', [Language.ML]: 'ഹലോ', [Language.PA]: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ', [Language.AS]: 'নমস্কাৰ' },
  'scan_crop': { [Language.EN]: 'Scan Crop', [Language.HI]: 'फसल स्कैन करें', [Language.BN]: 'ফসল স্ক্যান করুন', [Language.MR]: 'पीक स्कॅन करा', [Language.TE]: 'పంటను స్కాన్ చేయండి', [Language.TA]: 'பயிரை ஸ்கேன் செய்க', [Language.GU]: 'પાક સ્કેન કરો', [Language.UR]: 'فصل اسکین کریں', [Language.KN]: 'ಬೆಳೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ', [Language.OR]: 'ଫସଲ ସ୍କାନ କରନ୍ତୁ', [Language.ML]: 'വിള സ്കാൻ ചെയ്യുക', [Language.PA]: 'ਫਸਲ ਸਕੈਨ ਕਰੋ', [Language.AS]: 'শস্য স্কেন কৰক' },
  'field_notes': { [Language.EN]: 'Field Notes', [Language.HI]: 'खेत के नोट्स', [Language.BN]: 'ফিল্ড নোট', [Language.MR]: 'शेत नोंदी', [Language.TE]: 'ఫీల్డ్ నోట్స్', [Language.TA]: 'வயல் குறிப்புகள்', [Language.GU]: 'ક્ષેત્ર નોંધો', [Language.UR]: 'فیلڈ نوٹس', [Language.KN]: 'ಕ್ಷೇತ್ರ ಟิಪ್ಪಣಿಗಳು', [Language.OR]: 'କ୍ଷେତ୍ର ନୋଟ୍ସ', [Language.ML]: 'ഫീൽഡ് കുറിപ്പുകൾ', [Language.PA]: 'ਖੇਤ ਦੇ ਨੋਟ', [Language.AS]: 'ক্ষেত্ৰৰ টোকা' },
  'weather_current': { [Language.EN]: 'Current Weather', [Language.HI]: 'वर्तमान मौसम', [Language.BN]: 'বর্তমান আবহাওয়া', [Language.MR]: 'सध्याचे हवामान', [Language.TE]: 'ప్రస్తుత వాతావరణం', [Language.TA]: 'தற்போதைய வானிலை', [Language.GU]: 'વર્તમાન હવામાન', [Language.UR]: 'موجودہ موسم', [Language.KN]: 'ಪ್ರಸ್ತುತ ಹವಾಮಾನ', [Language.OR]: 'ବର୍ତ୍ତମାନର ପାଣିପାଗ', [Language.ML]: 'നിലവിലെ കാലാവസ്ഥ', [Language.PA]: 'ਮੌਜੂਦਾ ਮੌਸਮ', [Language.AS]: 'বৰ্তমানৰ বতৰ' },
  'humidity': { [Language.EN]: 'Humidity', [Language.HI]: 'नमी', [Language.BN]: 'আর্দ্রতা', [Language.MR]: 'आद्रता', [Language.TE]: 'తేమ', [Language.TA]: 'ஈரப்பதம்', [Language.GU]: 'ભેજ', [Language.UR]: 'نمی', [Language.KN]: 'ತೇವಾಂಶ', [Language.OR]: 'ଆର୍ଦ୍ରତା', [Language.ML]: 'ഈർപ്പം', [Language.PA]: 'ਨਮੀ', [Language.AS]: 'আৰ্দ্ৰতা' },
  'wind': { [Language.EN]: 'Wind', [Language.HI]: 'हवा', [Language.BN]: 'বাতাস', [Language.MR]: 'वारा', [Language.TE]: 'గాలి', [Language.TA]: 'காற்று', [Language.GU]: 'પવન', [Language.UR]: 'ہوا', [Language.KN]: 'ಗಾಳಿ', [Language.OR]: 'ପବନ', [Language.ML]: 'കാറ്റ്', [Language.PA]: 'ਹਵਾ', [Language.AS]: 'বতাহ' },
  'recent_alerts': { [Language.EN]: 'Recent Alerts', [Language.HI]: 'हालिया अलर्ट', [Language.BN]: 'সাম্প্রতিক সতর্কতা', [Language.MR]: 'अलीकडील सूचना', [Language.TE]: 'ఇటీవలి హెచ్చరికలు', [Language.TA]: 'சமீபத்திய விழிப்பூட்டல்கள்', [Language.GU]: 'તાજેતરની એલર્ટ', [Language.UR]: 'حالیہ الرٹس', [Language.KN]: 'ಇತ್ತೀಚಿನ ಎಚ್ಚರಿಕೆಗಳು', [Language.OR]: 'ସାମ୍ପ୍ରତିକ ସତର୍କତା', [Language.ML]: 'സമീപകാല അലേർട്ടുകൾ', [Language.PA]: 'ਤਾਜ਼ਾ ਅਲਰਟ', [Language.AS]: 'শেহতীয়া সতৰ্কবাণী' },

  // Crop Doctor
  'analyzing': { [Language.EN]: 'Analyzing plant biology...', [Language.HI]: 'पौधों के जीव विज्ञान का विश्लेषण...', [Language.BN]: 'উদ্ভিদ জীববিদ্যা বিশ্লেষণ...', [Language.MR]: 'वनस्पती जीवशास्त्राचे विश्लेषण...', [Language.TE]: 'మొక్కల జీవశాస్త్రం విశ్లేషిస్తోంది...', [Language.TA]: 'தாவர உயிரியலை ஆய்வு செய்கிறது...', [Language.GU]: 'વનસ્પતિ જીવવિજ્ઞાનનું విశ్લેષણ...', [Language.UR]: 'پودوں کی حیاتیات کا تجزیہ...', [Language.KN]: 'ಸಸ್ಯ ಜೀವಶಾಸ್ತ್ರವನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...', [Language.OR]: 'ଉଦ୍ଭିଦ ଜୀବବିଜ୍ଞାନ ବିଶ୍ଳେଷଣ...', [Language.ML]: 'സസ്യ ജീവശാസ്ത്രം വിശകലനം ചെയ്യുന്നു...', [Language.PA]: 'ਪੌਦੇ ਦੀ ਜੀਵ ਵਿਗਿਆਨ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ...', [Language.AS]: 'উদ্ভিদ জীৱবিজ্ঞান বিশ্লেষণ...' },
  'treatment': { [Language.EN]: 'Treatment', [Language.HI]: 'उपचार', [Language.BN]: 'চিকিৎসা', [Language.MR]: 'उपचार', [Language.TE]: 'చికిత్స', [Language.TA]: 'சிகிச்சை', [Language.GU]: 'સારવાર', [Language.UR]: 'علاج', [Language.KN]: 'ಚಿಕಿತ್ಸೆ', [Language.OR]: 'ଚିକିତ୍ସା', [Language.ML]: 'ചികിത്സ', [Language.PA]: 'ਇਲਾਜ', [Language.AS]: 'চিকিৎসা' },
  'natural_treatment': { [Language.EN]: 'Natural Treatment', [Language.HI]: 'प्राकृतिक उपचार', [Language.BN]: 'প্রাকৃতিক চিকিৎসা', [Language.MR]: 'नैसर्गिक उपचार', [Language.TE]: 'సహజ చికిత్స', [Language.TA]: 'இயற்கை சிகிச்சை', [Language.GU]: 'કુદરતી સારવાર', [Language.UR]: 'قدرتی علاج', [Language.KN]: 'ನೈಸರ್ಗಿಕ ಚಿಕಿತ್ಸೆ', [Language.OR]: 'ପ୍ରାକୃତିକ ଚିକିତ୍ସା', [Language.ML]: 'പ്രകൃതിദത്ത ചികിത്സ', [Language.PA]: 'ਕੁਦਰਤੀ ಇਲਾਜ', [Language.AS]: 'প্ৰাকৃতিক চিকিৎসা' },
  'chemical_treatment': { [Language.EN]: 'Chemical Treatment', [Language.HI]: 'रासायनिक उपचार', [Language.BN]: 'রাসায়নিক চিকিৎসা', [Language.MR]: 'रासायनिक उपचार', [Language.TE]: 'రసాయన చికిత్స', [Language.TA]: 'ரசாயன சிகிச்சை', [Language.GU]: 'રાસાયણિક સારવાર', [Language.UR]: 'کیمیائی علاج', [Language.KN]: 'ರಾಸಾಯನಿಕ ಚಿಕಿತ್ಸೆ', [Language.OR]: 'ରାସାୟନିକ ଚିକିତ୍ସା', [Language.ML]: 'രാസ ചികിത്സ', [Language.PA]: 'ਰਸਾਇਣਕ ਇਲਾਜ', [Language.AS]: 'ৰাসায়নিক চিকিৎসা' },
  'scan_another': { [Language.EN]: 'Scan Another Crop', [Language.HI]: 'एक और फसल को स्कैन करें', [Language.BN]: 'অন্য একটি ফসল স্ক্যান করুন', [Language.MR]: 'दुसरे पीक स्कॅन करा', [Language.TE]: 'మరొక పంటను స్కాన్ చేయండి', [Language.TA]: 'மற்றொரு பயிரை ஸ்கேன் செய்க', [Language.GU]: 'બીજો પાક સ્કેન કરો', [Language.UR]: 'دوسری فصل اسکین کریں', [Language.KN]: 'ಮತ್ತೊಂದು ಬೆಳೆಯನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ', [Language.OR]: 'ଅନ୍ୟ ଏକ ଫସଲ ସ୍କାନ କରନ୍ତୁ', [Language.ML]: 'മറ്റൊരു വിള സ്കാൻ ചെയ്യുക', [Language.PA]: 'ਦੂਜੀ ਫਸਲ ਸਕੈਨ ਕਰੋ', [Language.AS]: 'আন এটা শস্য স্কেন কৰক' },

  // Notes
  'new_btn': { [Language.EN]: 'New', [Language.HI]: 'नया', [Language.BN]: 'নতুন', [Language.MR]: 'नवीन', [Language.TE]: 'కొత్తది', [Language.TA]: 'புதிய', [Language.GU]: 'નવું', [Language.UR]: 'نیا', [Language.KN]: 'ಹೊಸದು', [Language.OR]: 'ନୂତନ', [Language.ML]: 'പുതിയത്', [Language.PA]: 'ਨਵਾਂ', [Language.AS]: 'নতুন' },
  'search_notes': { [Language.EN]: 'Search notes...', [Language.HI]: 'नोट्स खोजें...', [Language.BN]: 'নোট খুঁজুন...', [Language.MR]: 'नोंदी शोधा...', [Language.TE]: 'నోట్స్ వెతకండి...', [Language.TA]: 'குறிப்புகளைத் தேடுங்கள்...', [Language.GU]: 'નોંધો શોધો...', [Language.UR]: 'نوٹس تلاش کریں...', [Language.KN]: 'ಟಿಪ್ಪಣಿಗಳನ್ನು ಹುಡುಕಿ...', [Language.OR]: 'ନୋଟ୍ସ ଖୋଜନ୍ତୁ...', [Language.ML]: 'കുറിപ്പുകൾ തിരയുക...', [Language.PA]: 'ਨੋਟ ਖੋਜੋ...', [Language.AS]: 'টোকা সন্ধান কৰক...' },
  'edit_note': { [Language.EN]: 'Edit Note', [Language.HI]: 'नोट संपादित करें', [Language.BN]: 'নোট সম্পাদনা করুন', [Language.MR]: 'नोंद संपादित करा', [Language.TE]: 'నోట్ సవరించండి', [Language.TA]: 'குறிப்பைத் தொகு', [Language.GU]: 'નોંધ સંપાદિત કરો', [Language.UR]: 'نوٹ میں ترمیم کریں', [Language.KN]: 'ಟಿಪ್ಪಣಿ ಸಂಪಾದಿಸಿ', [Language.OR]: 'ନୋଟ୍ ସଂଶୋଧନ କରନ୍ତୁ', [Language.ML]: 'കുറിപ്പ് എഡിറ്റ് ചെയ്യുക', [Language.PA]: 'ਨੋਟ ਸੋਧੋ', [Language.AS]: 'টোকা সম্পাদনা কৰক' },
  'new_note': { [Language.EN]: 'New Note', [Language.HI]: 'नया नोट', [Language.BN]: 'নতুন নোট', [Language.MR]: 'नवीन नोंद', [Language.TE]: 'కొత్త నోట్', [Language.TA]: 'புதிய குறிப்பு', [Language.GU]: 'નવી નોંધ', [Language.UR]: 'نیا نوٹ', [Language.KN]: 'ಹೊಸ ಟಿಪ್ಪಣಿ', [Language.OR]: 'ନୂତନ ନୋଟ୍', [Language.ML]: 'പുതിയ കുറിപ്പ്', [Language.PA]: 'ਨਵਾਂ ਨੋਟ', [Language.AS]: 'নতুন টোকা' },
  'title_label': { [Language.EN]: 'Title', [Language.HI]: 'शीर्षक', [Language.BN]: 'শিরোনাম', [Language.MR]: 'शीर्षक', [Language.TE]: 'శీర్షిక', [Language.TA]: 'தலைப்பு', [Language.GU]: 'શીર્ષક', [Language.UR]: 'عنوان', [Language.KN]: 'ಶೀರ್ಷಿಕೆ', [Language.OR]: 'ଶୀର୍ଷକ', [Language.ML]: 'തലക്കെട്ട്', [Language.PA]: 'ਸਿਰਲੇਖ', [Language.AS]: 'শীৰ্ষক' },
  'category_label': { [Language.EN]: 'Category', [Language.HI]: 'श्रेणी', [Language.BN]: 'বিভাগ', [Language.MR]: 'वर्ग', [Language.TE]: 'వర్గం', [Language.TA]: 'வகை', [Language.GU]: 'કેટેગરી', [Language.UR]: 'زمرہ', [Language.KN]: 'ವರ್ಗ', [Language.OR]: 'ଶ୍ରେଣୀ', [Language.ML]: 'വിഭാഗം', [Language.PA]: 'ਸ਼੍ਰੇਣੀ', [Language.AS]: 'শ্ৰেণী' },
  'observations_label': { [Language.EN]: 'Observations', [Language.HI]: 'अवलोकन', [Language.BN]: 'পর্যবেক্ষণ', [Language.MR]: 'निरीक्षणे', [Language.TE]: 'పరిశీలనలు', [Language.TA]: 'அவதானிப்புகள்', [Language.GU]: 'અવલોકનો', [Language.UR]: 'مشاہدات', [Language.KN]: 'ವೀಕ್ಷಣೆಗಳು', [Language.OR]: 'ପର୍ଯ୍ୟବେକ୍ଷଣ', [Language.ML]: 'നിരീക്ഷണങ്ങൾ', [Language.PA]: 'ਨਿਰੀਖਣ', [Language.AS]: 'পৰ্যবেক্ষণ' },
  'save_note': { [Language.EN]: 'Save Note', [Language.HI]: 'नोट सहेजें', [Language.BN]: 'নোট সেভ করুন', [Language.MR]: 'नोंद जतन करा', [Language.TE]: 'నోట్ సేవ్ చేయండి', [Language.TA]: 'குறிப்பைச் சேமி', [Language.GU]: 'નોંધ સાચવો', [Language.UR]: 'نوٹ محفوظ کریں', [Language.KN]: 'ಟಿಪ್ಪಣಿ ಉಳಿಸಿ', [Language.OR]: 'ନୋଟ୍ ସଂରକ୍ଷିତ କରନ୍ତୁ', [Language.ML]: 'കുറിപ്പ് സേവ് ചെയ്യുക', [Language.PA]: 'ਨੋਟ ਸੰਭਾਲੋ', [Language.AS]: 'টোকা সংৰক্ষণ কৰক' },
  'update_note': { [Language.EN]: 'Update Note', [Language.HI]: 'नोट अपडेट करें', [Language.BN]: 'নোট আপডেট করুন', [Language.MR]: 'नोंद अपडेट करा', [Language.TE]: 'నోట్ అప్‌డేట్ చేయండి', [Language.TA]: 'குறிப்பை இடு', [Language.GU]: 'નોંધ અપડેટ કરો', [Language.UR]: 'نوٹ اپ ڈیٹ کریں', [Language.KN]: 'ಟಿಪ್ಪಣಿ ಅಪ್‌ಡೇಟ್ ಮಾಡಿ', [Language.OR]: 'ନୋଟ୍ ଅପଡେଟ୍ କରନ୍ତୁ', [Language.ML]: 'കുറിപ്പ് അപ്‌ഡേറ്റ് ചെയ്യുക', [Language.PA]: 'ਨੋਟ ਅਪਡੇਟ ਕਰੋ', [Language.AS]: 'টোকা আপডেট কৰক' },
  'no_notes_found': { [Language.EN]: 'No notes found.', [Language.HI]: 'कोई नोट नहीं मिला।', [Language.BN]: 'কোনো নোট পাওয়া যায়নি।', [Language.MR]: 'कोणत्याही नोंदी आढळल्या नाहीत.', [Language.TE]: 'నోట్స్ ఏవీ లేవు.', [Language.TA]: 'குறிப்புகள் எதுவும் கிடைக்கவில்லை.', [Language.GU]: 'કોઈ નોંધ મળી નથી.', [Language.UR]: 'کوئی نوٹ نہیں ملا۔', [Language.KN]: 'ಯಾವುದೇ ಟಿಪ್ಪಣಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ.', [Language.OR]: 'କୌଣସି ନୋଟ୍ ମିଳିଲା ନାହିଁ ।', [Language.ML]: 'കുറിപ്പുകളൊന്നും കണ്ടെത്തിയില്ല.', [Language.PA]: 'ਕੋਈ ਨੋਟ ਨਹੀਂ ਮਿਲਿਆ।', [Language.AS]: 'কোনো টোকা পোৱা নগ’ল।' },
  
  // Expert Support
  'ask_expert': { [Language.EN]: 'Ask an Agronomist', [Language.HI]: 'कृषि विशेषज्ञ से पूछें', [Language.BN]: 'একজন কৃষিবিদের কাছে জিজ্ঞাসা করুন', [Language.MR]: 'कृषी तज्ज्ञांना विचारा', [Language.TE]: 'వ్యవసాయ శాస్త్రవేత్తను అడగండి', [Language.TA]: 'ஒரு விவசாயியிடம் கேளுங்கள்', [Language.GU]: 'કૃષિ નિષ્ણાતને પૂછો', [Language.UR]: 'ماہر زراعت سے پوچھیں', [Language.KN]: 'ಕೃಷಿ ತಜ್ಞರನ್ನು ಕೇಳಿ', [Language.OR]: 'କୃଷି ବିଶେଷଜ୍ଞଙ୍କୁ ପଚାରନ୍ତୁ', [Language.ML]: 'ഒരു അഗ്രോണമിസ്റ്റിനോട് ചോദിക്കുക', [Language.PA]: 'ਖੇਤੀ ਮਾਹਰ ਨੂੰ ਪੁੱਛੋ', [Language.AS]: 'এগ্ৰনমিষ্টক সোধক' },
  'expert_desc': { [Language.EN]: 'Get advice from certified agricultural experts.', [Language.HI]: 'प्रमाणित कृषि विशेषज्ञों से सलाह लें।', [Language.BN]: 'প্রত্যয়িত কৃষি বিশেষজ্ঞদের কাছ से পরামর্শ নিন।', [Language.MR]: 'प्रमाणित कृषी तज्ज्ञांकडून सल्ला घ्या.', [Language.TE]: 'సర్టిఫైడ్ వ్యవసాయ నిపుణుల నుండి సలహా పొందండి.', [Language.TA]: 'சான்றளிக்கப்பட்ட விவசாய நிபுணர்களிடமிருந்து ஆலோசனை பெறவும்.', [Language.GU]: 'પ્રમાણિત કૃષિ નિષ્ણાતો પાસેથી સલાહ લો.', [Language.UR]: 'تصدیق شدہ زرعی ماہرین سے مشورہ حاصل کریں۔', [Language.KN]: 'ಪ್ರಮಾಣೀಕೃತ ಕೃಷಿ ತಜ್ಞರಿಂದ ಸಲಹೆ ಪಡೆಯಿರಿ.', [Language.OR]: 'ପ୍ରମାଣିତ କୃଷି ବିଶେଷଜ୍ଞଙ୍କଠାରୁ ପରାମର୍ଶ ନିଅନ୍ତୁ ।', [Language.ML]: 'സാക്ഷ്യപ്പെടുത്തിയ കാർഷിക വിദഗ്ധരിൽ നിന്ന് ഉപദേശം സ്വീകരിക്കുക.', [Language.PA]: 'ਪ੍ਰਮਾਣਿਤ ਖੇਤੀ ਮਾਹਰਾਂ ਤੋਂ ਸਲਾਹ ਲਓ।', [Language.AS]: 'প্ৰমাণিত কৃষি বিশেষজ্ঞৰ পৰা পৰামৰ্শ লওক।' },
  'request_sent': { [Language.EN]: 'Request Sent!', [Language.HI]: 'अनुरोध भेजा गया!', [Language.BN]: 'অনুরোধ পাঠানো হয়েছে!', [Language.MR]: 'विनंती पाठवली!', [Language.TE]: 'అభ్యర్థన పంపబడింది!', [Language.TA]: 'கோரிக்கை அனுப்பப்பட்டது!', [Language.GU]: 'વિનંતી મોકલવામાં આવી!', [Language.UR]: 'درخواست بھیج دی گئی!', [Language.KN]: 'ವಿನಂತಿ ಸಲ್ಲಿಸಲಾಗಿದೆ!', [Language.OR]: 'ଅନୁରୋଧ ପଠାଗଲା!', [Language.ML]: 'അപേക്ഷ അയച്ചു!', [Language.PA]: 'ਬੇਨਤੀ ਭੇਜੀ ਗਈ!', [Language.AS]: 'অনুৰোধ পঠিওৱা হ’ল!' },
  'subject_label': { [Language.EN]: 'Subject', [Language.HI]: 'विषय', [Language.BN]: 'বিষয়', [Language.MR]: 'विषय', [Language.TE]: 'విషయం', [Language.TA]: 'பொருள்', [Language.GU]: 'વિષય', [Language.UR]: 'موضوع', [Language.KN]: 'ವಿಷಯ', [Language.OR]: 'ବିଷୟ', [Language.ML]: 'വിഷയം', [Language.PA]: 'ਵਿਸ਼ਾ', [Language.AS]: 'বিষয়' },
  'description_label': { [Language.EN]: 'Description', [Language.HI]: 'विवरण', [Language.BN]: 'বর্ণনা', [Language.MR]: 'वर्णन', [Language.TE]: 'వివరణ', [Language.TA]: 'விளக்கம்', [Language.GU]: 'વર્ણન', [Language.UR]: 'تفصیل', [Language.KN]: 'ವಿವರಣೆ', [Language.OR]: 'ବିବରଣୀ', [Language.ML]: 'വിവരണം', [Language.PA]: 'ਵੇਰਵਾ', [Language.AS]: 'বিৱৰণ' },
  'submit_request': { [Language.EN]: 'Submit Request', [Language.HI]: 'अनुरोध जमा करें', [Language.BN]: 'অনুরোধ জমা দিন', [Language.MR]: 'विनंती सादर करा', [Language.TE]: 'అభ్యర్థనను సమర్పించండి', [Language.TA]: 'கோரிக்கையைச் சமர்ப்பி', [Language.GU]: 'વિનંતી સબમિટ કરો', [Language.UR]: 'درخواست جمع کروائیں', [Language.KN]: 'ವಿನಂತಿಯನ್ನು ಸಲ್ಲಿಸಿ', [Language.OR]: 'ଅନୁରୋଧ ଦାଖଲ କରନ୍ତୁ', [Language.ML]: 'അപേക്ഷ സമർപ്പിക്കുക', [Language.PA]: 'ਬੇਨਤੀ ਜਮ੍ਹਾਂ ਕਰੋ', [Language.AS]: 'অনুৰোধ জমা কৰক' },

  // Categories & Subjects
  'cat_general': { [Language.EN]: 'General', [Language.HI]: 'सामान्य', [Language.BN]: 'সাধারণ', [Language.MR]: 'सामान्य', [Language.TE]: 'సాధారణం', [Language.TA]: 'பொதுவானது', [Language.GU]: 'સામાન્ય', [Language.UR]: 'عام', [Language.KN]: 'ಸಾಮಾನ್ಯ', [Language.OR]: 'ସାଧାରଣ', [Language.ML]: 'സാധാരണം', [Language.PA]: 'ਆਮ', [Language.AS]: 'সাধাৰণ' },
  'cat_planting': { [Language.EN]: 'Planting', [Language.HI]: 'रोपण', [Language.BN]: 'রোপণ', [Language.MR]: 'लागवड', [Language.TE]: 'నాటడం', [Language.TA]: 'நடவு செய்தல்', [Language.GU]: 'રોપણી', [Language.UR]: 'پودے لگانا', [Language.KN]: 'ನಾಟಿ', [Language.OR]: 'ରୋପଣ', [Language.ML]: 'നടീൽ', [Language.PA]: 'ਬਿਜਾਈ', [Language.AS]: 'ৰোপণ' },
  'cat_irrigation': { [Language.EN]: 'Irrigation', [Language.HI]: 'सिंचाई', [Language.BN]: 'সেচ', [Language.MR]: 'सिंचन', [Language.TE]: 'నీటి పారుదల', [Language.TA]: 'நீர்ப்பாசனம்', [Language.GU]: 'સિંચાઈ', [Language.UR]: 'آبپاشی', [Language.KN]: 'ನೀರಾವರಿ', [Language.OR]: 'ଜଳସେଚନ', [Language.ML]: 'ജലസേചനം', [Language.PA]: 'ਸਿੰਚਾਈ', [Language.AS]: 'জলসিঞ্চন' },
  'cat_harvest': { [Language.EN]: 'Harvest', [Language.HI]: 'कटाई', [Language.BN]: 'ফসল সংগ্রহ', [Language.MR]: 'कापणी', [Language.TE]: 'కోత', [Language.TA]: 'அறுவடை', [Language.GU]: 'લણણી', [Language.UR]: 'کٹائی', [Language.KN]: 'ಕೊಯ್ಲು', [Language.OR]: 'ଅମଳ', [Language.ML]: 'വിളവെടുപ്പ്', [Language.PA]: 'ਵਾਢੀ', [Language.AS]: 'ফচল চপোৱা' },
  'cat_issue': { [Language.EN]: 'Issue', [Language.HI]: 'मुद्दा', [Language.BN]: 'সমস্যা', [Language.MR]: 'समस्या', [Language.TE]: 'సమస్య', [Language.TA]: 'சிக்கல்', [Language.GU]: 'મુશ્કેલી', [Language.UR]: 'مسئلہ', [Language.KN]: 'ಸಮಸ್ಯೆ', [Language.OR]: 'ସମସ୍ୟା', [Language.ML]: 'പ്രശ്നം', [Language.PA]: 'ਮੁੱਦਾ', [Language.AS]: 'সমস্যা' },
};
