import { Language } from '../types';

export const translations: Record<string, Record<Language, string>> = {
  // Common UI
  'app_title': { [Language.EN]: 'AgroAI', [Language.HI]: 'एग्रो एआई', [Language.BN]: 'এগ্রো এআই', [Language.MR]: 'एग्रो एआय', [Language.TE]: 'అగ్రో ఏఐ', [Language.TA]: 'அக்ரோ ஏஐ', [Language.GU]: 'એગ્રો એઆઈ', [Language.UR]: 'ایگرو اے آئی', [Language.KN]: 'ಅಗ್ರೋ ಎಐ', [Language.OR]: 'ଏଗ୍ରୋ ଏଆଇ', [Language.ML]: 'അഗ്രോ എഐ', [Language.PA]: 'ਐਗਰੋ ਏਆਈ', [Language.AS]: 'এগ্ৰো এআই' },
  'smart_farming': { [Language.EN]: 'Smart Farming Assistant', [Language.HI]: 'स्मार्ट खेती सहायक', [Language.BN]: 'স্মার্ট ফার্মিং সহকারী', [Language.MR]: 'स्मार्ट शेती सहाय्यक', [Language.TE]: 'స్మార్ట్ ఫార్మింగ్ అసిస్టెంట్', [Language.TA]: 'ஸ்மார்ட் விவசாய உதவியாளர்', [Language.GU]: 'સ્માર્ટ ફાર્મિંગ સહાયક', [Language.UR]: 'اسمارٹ فارمنگ اسسٹنٹ', [Language.KN]: 'ಸ್ಮಾರ್ಟ್ ಫಾರ್ಮಿಂಗ್ ಅಸಿಸ್ಟೆಂಟ್', [Language.OR]: 'ସ୍ମାର୍ଟ ଚାଷ ସହାୟକ', [Language.ML]: 'സ്മാർട്ട് ഫാമിംഗ് അസിസ്റ്റന്റ്', [Language.PA]: 'ਸਮਾਰਟ ਫਾਰਮਿੰਗ ਸਹਾਇਕ', [Language.AS]: 'স্মাৰ্ট ফাৰ্মিং সহায়ক' },
  
  // Navigation
  'nav_home': { [Language.EN]: 'Home', [Language.HI]: 'होम', [Language.BN]: 'হোম', [Language.MR]: 'होम', [Language.TE]: 'హోమ్', [Language.TA]: 'முகப்பு', [Language.GU]: 'હોમ', [Language.UR]: 'ہوم', [Language.KN]: 'ಹೋಮ್', [Language.OR]: 'ମୁଖ୍ୟ ପୃଷ୍ଠା', [Language.ML]: 'ഹോം', [Language.PA]: 'ਮੁੱਖ', [Language.AS]: 'গৃহ' },
  'nav_doctor': { [Language.EN]: 'Doctor', [Language.HI]: 'डॉक्टर', [Language.BN]: 'ডাক্তার', [Language.MR]: 'डॉक्टर', [Language.TE]: 'డాక్టర్', [Language.TA]: 'மருத்துவர்', [Language.GU]: 'ડોક્ટર', [Language.UR]: 'ڈاکٹر', [Language.KN]: 'ಡಾಕ್ಟರ್', [Language.OR]: 'ଡାକ୍ତର', [Language.ML]: 'ഡോക്ടർ', [Language.PA]: 'ਡਾਕਟਰ', [Language.AS]: 'চিকিৎসক' },
  'nav_notes': { [Language.EN]: 'Notes', [Language.HI]: 'नोट्स', [Language.BN]: 'নোট', [Language.MR]: 'नोंदी', [Language.TE]: 'నోట్స్', [Language.TA]: 'குறிப்புகள்', [Language.GU]: 'નોંધો', [Language.UR]: 'نوٹس', [Language.KN]: 'ಟಿಪ್ಪಣಿಗಳು', [Language.OR]: 'ନୋଟ୍ସ', [Language.ML]: 'കുറിപ്പുകൾ', [Language.PA]: 'ਨੋਟ', [Language.AS]: 'টোকা' },
  'nav_expert': { [Language.EN]: 'Expert', [Language.HI]: 'विशेषज्ञ', [Language.BN]: 'বিশেষজ্ঞ', [Language.MR]: 'तज्ज्ञ', [Language.TE]: 'నిపుణుడు', [Language.TA]: 'நிபுணர்', [Language.GU]: 'નિષ્ણાત', [Language.UR]: 'ماہر', [Language.KN]: 'ತಜ್ಞ', [Language.OR]: 'ବିଶେଷଜ୍ଞ', [Language.ML]: 'വിദഗ്ദ്ധൻ', [Language.PA]: 'ਮਾਹਰ', [Language.AS]: 'বিশেষজ্ঞ' },

  // Auth
  'login_welcome': { [Language.EN]: 'Welcome Back', [Language.HI]: 'स्वागत है', [Language.BN]: 'স্বাগতম', [Language.MR]: 'स्वागत आहे', [Language.TE]: 'స్వాగతం', [Language.TA]: 'வரவேற்பு', [Language.GU]: 'સ્વાગત છે', [Language.UR]: 'خوش آمدید', [Language.KN]: 'ಸ್ವಾಗತ', [Language.OR]: 'ସ୍ୱାଗତ', [Language.ML]: 'സ്വാഗതം', [Language.PA]: 'ਜੀ ਆਇਆਂ ਨੂੰ', [Language.AS]: 'স্বাগতম' },
  'create_account': { [Language.EN]: 'Create Farmer Account', [Language.HI]: 'किसान खाता बनाएं', [Language.BN]: 'কৃষক অ্যাকাউন্ট তৈরি করুন', [Language.MR]: 'शेतकरी खाते तयार करा', [Language.TE]: 'రైతు ఖాతాను సృష్టించండి', [Language.TA]: 'விவசாயி கணக்கை உருவாக்கு', [Language.GU]: 'ખેડૂત ખાતું બનાવો', [Language.UR]: 'کسان اکاؤنٹ بنائیں', [Language.KN]: 'ರೈತ ಖಾತೆಯನ್ನು ರಚಿಸಿ', [Language.OR]: 'ଚାଷୀ ଆକାଉଣ୍ଟ ଖୋଲନ୍ତୁ', [Language.ML]: 'കർഷക അക്കൗണ്ട് സൃഷ്ടിക്കുക', [Language.PA]: 'ਕਿਸਾਨ ਖਾਤਾ ਬਣਾਓ', [Language.AS]: 'কৃষক একাউণ্ট সৃষ্টি কৰক' },
  'login_to_farm': { [Language.EN]: 'Login to Farm', [Language.HI]: 'लॉगिन करें', [Language.BN]: 'লগইন করুন', [Language.MR]: 'लॉगिन करा', [Language.TE]: 'లాగిన్', [Language.TA]: 'உள்நுழைக', [Language.GU]: 'લોગિન કરો', [Language.UR]: 'لاگ ان کریں', [Language.KN]: 'ಲಾಗಿನ್ ಮಾಡಿ', [Language.OR]: 'ଲଗଇନ୍ କରନ୍ତୁ', [Language.ML]: 'ലോഗിൻ ചെയ്യുക', [Language.PA]: 'ਲੌਗਇਨ ਕਰੋ', [Language.AS]: 'লগইন কৰক' },
  'start_farming': { [Language.EN]: 'Start Farming', [Language.HI]: 'खेती शुरू करें', [Language.BN]: 'চাষ শুরু করুন', [Language.MR]: 'शेती सुरू करा', [Language.TE]: 'వ్యవసాయం ప్రారంభించండి', [Language.TA]: 'விவசாயத்தைத் தொடங்குங்கள்', [Language.GU]: 'ખેતી શરૂ કરો', [Language.UR]: 'کاشتکاری شروع کریں', [Language.KN]: 'ವ್ಯವಸಾಯ ಪ್ರಾರಂಭಿಸಿ', [Language.OR]: 'ଚାଷ ଆରମ୍ଭ କରନ୍ତୁ', [Language.ML]: 'കൃഷി ആരംഭിക്കുക', [Language.PA]: 'ਖੇਤੀਬਾੜੀ ਸ਼ੁਰੂ ਕਰੋ', [Language.AS]: 'খেতি আৰম্ভ কৰক' },

  // Dashboard
  'hello': { [Language.EN]: 'Hello', [Language.HI]: 'नमस्ते', [Language.BN]: 'হ্যালো', [Language.MR]: 'नमस्कार', [Language.TE]: 'హలో', [Language.TA]: 'வணக்கம்', [Language.GU]: 'હેલો', [Language.UR]: 'ہیلو', [Language.KN]: 'ಹಲೋ', [Language.OR]: 'ନମସ୍କାର', [Language.ML]: 'ഹലോ', [Language.PA]: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ', [Language.AS]: 'নমস্কাৰ' },
  'scan_crop': { [Language.EN]: 'Scan Crop', [Language.HI]: 'फसल स्कैन करें', [Language.BN]: 'ফসল স্ক্যান করুন', [Language.MR]: 'पीक स्कॅन करा', [Language.TE]: 'పంటను స్కాన్ చేయండి', [Language.TA]: 'பயிரை ஸ்கேன் செய்க', [Language.GU]: 'પાક સ્કેન કરો', [Language.UR]: 'فصل اسکین کریں', [Language.KN]: 'ಬೆಳೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ', [Language.OR]: 'ଫସଲ ସ୍କାନ କରନ୍ତୁ', [Language.ML]: 'വിള സ്കാൻ ചെയ്യുക', [Language.PA]: 'ਫਸਲ ਸਕੈਨ ਕਰੋ', [Language.AS]: 'শস্য স্কেন কৰক' },
  'field_notes': { [Language.EN]: 'Field Notes', [Language.HI]: 'खेत के नोट्स', [Language.BN]: 'ফিল্ড নোট', [Language.MR]: 'शेत नोंदी', [Language.TE]: 'ఫీల్డ్ నోట్స్', [Language.TA]: 'வயல் குறிப்புகள்', [Language.GU]: 'ક્ષેત્ર નોંધો', [Language.UR]: 'فیلڈ نوٹس', [Language.KN]: 'ಕ್ಷೇತ್ರ ಟಿಪ್ಪಣಿಗಳು', [Language.OR]: 'କ୍ଷେତ୍ର ନୋଟ୍ସ', [Language.ML]: 'ഫീൽഡ് കുറിപ്പുകൾ', [Language.PA]: 'ਖੇਤ ਦੇ ਨੋਟ', [Language.AS]: 'ক্ষেত্ৰৰ টোকা' },
  'weather_current': { [Language.EN]: 'Current Weather', [Language.HI]: 'वर्तमान मौसम', [Language.BN]: 'বর্তমান আবহাওয়া', [Language.MR]: 'सध्याचे हवामान', [Language.TE]: 'ప్రస్తుత వాతావరణం', [Language.TA]: 'தற்போதைய வானிலை', [Language.GU]: 'વર્તમાન હવામાન', [Language.UR]: 'موجودہ موسم', [Language.KN]: 'ಪ್ರಸ್ತುತ ಹವಾಮಾನ', [Language.OR]: 'ବର୍ତ୍ତମାନର ପାଣିପାଗ', [Language.ML]: 'നിലവിലെ കാലാവസ്ഥ', [Language.PA]: 'ਮੌਜੂਦਾ ਮੌਸਮ', [Language.AS]: 'বৰ্তমানৰ বতৰ' },
  'humidity': { [Language.EN]: 'Humidity', [Language.HI]: 'नमी', [Language.BN]: 'আর্দ্রতা', [Language.MR]: 'आद्रता', [Language.TE]: 'తేమ', [Language.TA]: 'ஈரப்பதம்', [Language.GU]: 'ભેજ', [Language.UR]: 'نمی', [Language.KN]: 'ತೇವಾಂಶ', [Language.OR]: 'ଆର୍ଦ୍ରତା', [Language.ML]: 'ഈർപ്പം', [Language.PA]: 'ਨਮੀ', [Language.AS]: 'আৰ্দ্ৰতা' },
  'wind': { [Language.EN]: 'Wind', [Language.HI]: 'हवा', [Language.BN]: 'বাতাস', [Language.MR]: 'वारा', [Language.TE]: 'గాలి', [Language.TA]: 'காற்று', [Language.GU]: 'પવન', [Language.UR]: 'ہوا', [Language.KN]: 'ಗಾಳಿ', [Language.OR]: 'ପବନ', [Language.ML]: 'കാറ്റ്', [Language.PA]: 'ਹਵਾ', [Language.AS]: 'বতাহ' },
  'recent_alerts': { [Language.EN]: 'Recent Alerts', [Language.HI]: 'हालिया अलर्ट', [Language.BN]: 'সাম্প্রতিক সতর্কতা', [Language.MR]: 'अलीकडील सूचना', [Language.TE]: 'ఇటీవలి హెచ్చరికలు', [Language.TA]: 'சமீபத்திய விழிப்பூட்டல்கள்', [Language.GU]: 'તાજેતરની એલર્ટ', [Language.UR]: 'حالیہ الرٹس', [Language.KN]: 'ಇತ್ತೀಚಿನ ಎಚ್ಚರಿಕೆಗಳು', [Language.OR]: 'ସାମ୍ପ୍ରତିକ ସତର୍କତା', [Language.ML]: 'സമീപകാല അലേർട്ടുകൾ', [Language.PA]: 'ਤਾਜ਼ਾ ਅਲਰਟ', [Language.AS]: 'শেহতীয়া সতৰ্কবাণী' },

  // Crop Doctor
  'analyzing': { [Language.EN]: 'Analyzing plant biology...', [Language.HI]: 'पौधों के जीव विज्ञान का विश्लेषण...', [Language.BN]: 'উদ্ভিদ জীববিদ্যা বিশ্লেষণ...', [Language.MR]: 'वनस्पती जीवशास्त्राचे विश्लेषण...', [Language.TE]: 'మొక్కల జీవశాస్త్రం విశ్లేషిస్తోంది...', [Language.TA]: 'தாவர உயிரியலை ஆய்வு செய்கிறது...', [Language.GU]: 'વનસ્પતિ જીવવિજ્ઞાનનું విశ్લેષણ...', [Language.UR]: 'پودوں کی حیاتیات کا تجزیہ...', [Language.KN]: 'ಸಸ್ಯ ಜೀವಶಾಸ್ತ್ರವನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...', [Language.OR]: 'ଉଦ್ଭିଦ ଜୀବବିଜ୍ଞାନ ବିଶ୍ଳେଷଣ...', [Language.ML]: 'സസ്യ ജീവശാസ്ത്രം വിശകലനം ചെയ്യുന്നു...', [Language.PA]: 'ਪੌਦੇ ਦੀ ਜੀਵ ਵਿਗਿਆਨ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ...', [Language.AS]: 'উদ্ভিদ জীৱবিজ্ঞান বিশ্লেষণ...' },
  'treatment': { [Language.EN]: 'Treatment', [Language.HI]: 'उपचार', [Language.BN]: 'চিকিৎসা', [Language.MR]: 'उपचार', [Language.TE]: 'చికిత్స', [Language.TA]: 'சிகிச்சை', [Language.GU]: 'સારવાર', [Language.UR]: 'علاج', [Language.KN]: 'ಚಿಕಿತ್ಸೆ', [Language.OR]: 'ଚିକିତ୍ସା', [Language.ML]: 'ചികിത്സ', [Language.PA]: 'ਇਲਾਜ', [Language.AS]: 'চিকিৎসা' },
  'natural_treatment': { [Language.EN]: 'Natural Treatment', [Language.HI]: 'प्राकृतिक उपचार', [Language.BN]: 'প্রাকৃতিক চিকিৎসা', [Language.MR]: 'नैसर्गिक उपचार', [Language.TE]: 'సహజ చికిత్స', [Language.TA]: 'இயற்கை சிகிச்சை', [Language.GU]: 'કુદરતી સારવાર', [Language.UR]: 'قدرتی علاج', [Language.KN]: 'ನೈಸರ್ಗಿಕ ಚಿಕಿತ್ಸೆ', [Language.OR]: 'ପ୍ରାକୃତିକ ଚିକିତ୍ସା', [Language.ML]: 'പ്രകൃതിദത്ത ചികിത്സ', [Language.PA]: 'ਕੁਦਰਤੀ ਇਲਾਜ', [Language.AS]: 'প্ৰাকৃতিক চিকিৎসা' },
  'chemical_treatment': { [Language.EN]: 'Chemical Treatment', [Language.HI]: 'रासायनिक उपचार', [Language.BN]: 'রাসায়নিক চিকিৎসা', [Language.MR]: 'रासायनिक उपचार', [Language.TE]: 'రసాయన చికిత్స', [Language.TA]: 'ரசாயன சிகிச்சை', [Language.GU]: 'રાસાયણિક સારવાર', [Language.UR]: 'کیمیائی علاج', [Language.KN]: 'ರಾಸಾಯನಿಕ ಚಿಕಿತ್ಸೆ', [Language.OR]: 'ରାସାୟନିକ ଚିକିତ୍ସା', [Language.ML]: 'രാസ ചികിത്സ', [Language.PA]: 'ਰਸਾਇਣਕ ਇਲਾਜ', [Language.AS]: 'ৰাসায়নিক চিকিৎসা' },
};